version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        ports:
            - "9000:9000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:eyMRtgkjiqUdDplGP5ZjIE7WttdkBSlXzv1bOSUBKIs=
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db
    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - db-data:/var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            - PMA_HOST=db
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "8080:80"
        networks:
            - app-network

volumes:
    db-data:
        driver: local

networks:
    app-network:
        driver: bridge
